<?xml version="1.0" encoding="utf-8"?><Database Name="QLPKDY" Class="QLPKDYDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=savitar\sqlexpress;Initial Catalog=QLPKDY;Integrated Security=True" SettingsObjectName="QuanLyPhongKhamDongY.Properties.Settings" SettingsPropertyName="QLPKDYConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BenhNhan" Member="BenhNhans">
    <Type Name="BenhNhan">
      <Column Name="MaBN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="BenhNhan_DonThuoc" Member="DonThuocs" ThisKey="MaBN" OtherKey="MaBN" Type="DonThuoc" />
    </Type>
  </Table>
  <Table Name="dbo.Thuoc" Member="Thuocs">
    <Type Name="Thuoc">
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuyCach" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CongDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CachDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NSX" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HSD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Thuoc_ChiTietDonThuoc" Member="ChiTietDonThuocs" ThisKey="MaThuoc" OtherKey="MaThuoc" Type="ChiTietDonThuoc" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonThuoc" Member="ChiTietDonThuocs">
    <Type Name="ChiTietDonThuoc">
      <Column Name="MaCTDT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Thuoc_ChiTietDonThuoc" Member="Thuoc" ThisKey="MaThuoc" OtherKey="MaThuoc" Type="Thuoc" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="DonThuoc_ChiTietDonThuoc" Member="DonThuoc" ThisKey="MaDT" OtherKey="MaDT" Type="DonThuoc" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DonThuoc" Member="DonThuocs">
    <Type Name="DonThuoc">
      <Column Name="MaDT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaBN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="DonThuoc_ChiTietDonThuoc" Member="ChiTietDonThuocs" ThisKey="MaDT" OtherKey="MaDT" Type="ChiTietDonThuoc" />
      <Association Name="BenhNhan_DonThuoc" Member="BenhNhan" ThisKey="MaBN" OtherKey="MaBN" Type="BenhNhan" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TDN" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>